version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "/src/templates/app"
    update_schedule: "live"
    target_branch: "master"