trigger:
    branches:
        include:
            - master
    paths:
        include:
            - frontend/Apps/TEMPLATE_APP_KEY/package.json

# DEFINES THE RESOURCES FOR BUILD AND DEPLOY TEMPLATE (CANNOT BE DEFINED IN TEMLATES, MUST BE DEFINED IN ROOT)
resources:
    repositories:
        - repository: fusion-pipeline-templates
          type: git
          name: fusion-pipeline-templates
          ref: refs/heads/feature/use-v2-of-fusion-app-task

stages:
    - template: ../../pipelines/templates/build-and-deploy-single-app.yml
      parameters:
          appKey: TEMPLATE_APP_KEY
          appName: TEMPLATE_APP_NAME
