name: PR Build

on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup node and install deps
        uses: ./.github/workflows/actions/node-setup
      
      - name: Build project
        run:
          pnpm run build
