name: Beta publish

on:
  release:
    types: 
      - prereleased
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup node and install deps
        uses: ./.github/workflows/actions/node-setup

      - name: pnpm build
        run:
          pnpm run build

      - name: pnpm publish
        run: pnpm publish --access public --tag next
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
