name: Bundle and publish

on:
  release:
    types: 
      - published
      
jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup node and install deps
        uses: ./.github/workflows/actions/node-setup
      
      - name: pnpm build and publish
        run: | 
          pnpm run update-templates
          pnpm run build
          pnpm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          pnpm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
